//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApliBinarios
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pubsEntities1 : DbContext
    {
        public pubsEntities1()
            : base("name=pubsEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<authors> authors { get; set; }
        public DbSet<employee> employee { get; set; }
        public DbSet<jobs> jobs { get; set; }
        public DbSet<pub_info> pub_info { get; set; }
        public DbSet<publishers> publishers { get; set; }
        public DbSet<sales> sales { get; set; }
        public DbSet<stores> stores { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<titleauthor> titleauthor { get; set; }
        public DbSet<titles> titles { get; set; }
        public DbSet<discounts> discounts { get; set; }
        public DbSet<roysched> roysched { get; set; }
    }
}
