//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApliBinarios
{
    using System;
    using System.Collections.Generic;
    
    public partial class roysched
    {
        public string title_id { get; set; }
        public Nullable<int> lorange { get; set; }
        public Nullable<int> hirange { get; set; }
        public Nullable<int> royalty { get; set; }
    
        public virtual titles titles { get; set; }
    }
}
